### ISSUE TITLE
[BUG] - TypeError

### ISSUE THREAD

**Issue by fatualux** [nickprock/ccat_semantic_chunking#3]
**Describe the bug**
Good morning and thank you for your work.

Activating the plugin with default settings, I get this error:

```python
TypeError: cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object
```

The chunks are created, but the error is always raised.

**To Reproduce**
1. Simply activate the plugin
2. Upload a PDF file to the Cat
3. Complete traceback:
```python
CheshireCat-dev          | Traceback (most recent call last):
CheshireCat-dev          |   File "/app/cat/mad_hatter/mad_hatter.py", line 273, in execute_hook
CheshireCat-dev          |     deepcopy(tea_cup), *deepcopy(args[1:]), cat=cat
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
CheshireCat-dev          |     y = _reconstruct(x, memo, *rv)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
CheshireCat-dev          |     state = deepcopy(state, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
CheshireCat-dev          |     y = _reconstruct(x, memo, *rv)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
CheshireCat-dev          |     state = deepcopy(state, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
CheshireCat-dev          |     y = _reconstruct(x, memo, *rv)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
CheshireCat-dev          |     state = deepcopy(state, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
CheshireCat-dev          |     y = _reconstruct(x, memo, *rv)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
CheshireCat-dev          |     state = deepcopy(state, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
CheshireCat-dev          |     y = _reconstruct(x, memo, *rv)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
CheshireCat-dev          |     state = deepcopy(state, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
CheshireCat-dev          |     y = copier(x, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
CheshireCat-dev          |     y[deepcopy(key, memo)] = deepcopy(value, memo)
CheshireCat-dev          |   File "/usr/local/lib/python3.10/copy.py", line 161, in deepcopy
CheshireCat-dev          |     rv = reductor(4)
CheshireCat-dev          | TypeError: cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object
```

**Expected behavior**
The documents are split and no errors are raised

**Additional context**
Configuration:
```python
        breakpoint_threshold_type="percentile",
        breakpoint_threshold_amount: Optional[float] = 95
```

Thanks in advance for your attention.
If I find a solution I will make a PR

**Comment by nickprock** [comment]
Hi @fatualux I know the bug. I think that it appears because semantic chunking Is experimental in langchain. For a while the message had disappeared now it is back, but as you write the method works.
